### ISSUE TITLE
Excelente trabajo!

### ISSUE THREAD

**Issue by fzmolina** [javierlopeza/datos-coronavirus-chile#58]
Hola!

Tienen un muy buen trabajo, felicitaciones!

Estaba viendo su parser del informe epidemiológico, y está copiando sólo los datos de los casos activos. Me gustaría contribuir a copiar el resto de los campos, específicamente el número de casos según la fecha de inicio de síntomas, en las semanas epidemiológicas.

Saludos!

**Comment by javierlopeza** [comment]
Hola @fzmolina, muchas gracias por tus comentarios!
Feliz de recibir contribuciones al repo, por el momento solo extraemos los casos activos pues son los que se visualizan en la página.

Una pregunta, los que trabajan en el repo [MinCiencia/Datos-COVID19](https://github.com/MinCiencia/Datos-COVID19), ¿tienen acceso a otras fuentes de datos que no sean estos archivos PDF (reporte diario e informe epidemiológico)?
Me imaginaba que recibían de manera interna archivos CSV o podían consultar alguna BD privada.

**Comment by fzmolina** [comment]
Genial!,

Yo estoy comenzando a trabajar sobre la información de las otras columnas. La fecha de inicio de síntomas es la parte que más me interesa.

Sobre tu pregunta, en el "¿cómo lo hacemos?" del readme del repo del MinCiencia se muestra el procedimiento: "Para el caso de los pdfs, transcribimos los contenidos para generar archivos CSV, que son utilizados para generar los productos relevantes.". Se utilizan los datos que son públicos y de la misma manera que se ofrecen al público en general.
