### ISSUE TITLE
Parseando todas las tablas:Reporte Diario tabla 1

### ISSUE THREAD

**Issue by scornejob** [javierlopeza/datos-coronavirus-chile#95]
Hola @javierlopeza 

En la linea del https://github.com/javierlopeza/datos-coronavirus-chile/issues/58, tengo un branch en nuestro fork que parsea y entrega la tabla1 bien. 
Te interesa incorporar eso a tu repo?
Nos gustaría abrir la colaboracion y sumar más actores (si aparecen interesados) y no tenemos claro si dirigirlos aca, o mantenerlos en nuestro fork y despues hacerte PRs, o seguir desacoplados

**Comment by scornejob** [comment]
Y me puedes decir a que branch apunto mi PR? yo hice el branch desde master.

**Comment by javierlopeza** [comment]
Hola @scornejob! Siempre se agradece la colaboración. Agregué la branch [colab](https://github.com/javierlopeza/datos-coronavirus-chile/tree/colab) y la dejé como la default para juntar todas las colaboraciones que se construyan sobre este repo. Así podemos mantener intactas las branches master y production que son consumidas por https://covid19entucomuna.cl/

**Comment by scornejob** [comment]
Super.

Entonces voy a alinear mi branch con ese.
En cuanto al orden del código: tienes alguna preferencia para añadir nuestra colaboracion? En este momento estoy desarrollando sobre la clase reporte_parser.py, pero dado que lo usas para tu sistema en produccion, quizas es mas limpio que cree una clase aparte, y herede desde la tuya.

Entonces, mi propuesta es añadir un directorio DO,  y hacer ahí las clases que generan CSVs a partir de todas las tablas. Cuando tenga el refactor, te aviso.

**Comment by scornejob** [comment]
aca:
https://github.com/javierlopeza/datos-coronavirus-chile/pull/97
